language: bash
sudo: required
services:
  - docker
env:
  - STACK=heroku-18
  - STACK=heroku-16
  - STACK=cedar-14
install: docker pull "heroku/${STACK/-/:}"
script: docker run -v $(pwd):/plugin:ro --rm -it heroku/${STACK/-/:} bash -c "cp -r /plugin /plugin_build; cd /plugin_build; ./build.sh $STACK 8.x"