language: node_js
sudo: false
node_js:
- '8'
- '9'
- '10'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - gcc-4.8-multilib
    - g++-4.8-multilib
    - gcc-multilib
    - g++-multilib
os:
- linux
after_success:
- ./deploy.sh
