language: node_js
sudo: false
node_js:
- '8'
- '9'
- '10'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - gcc-4.8-multilib
    - g++-4.8-multilib
    - gcc-multilib
    - g++-multilib
os:
- linux
before_deploy:
- ARCHIVE_NAME="\${TRAVIS_TAG:-latest}-$TRAVIS_OS_NAME-\`uname -m\`.tar"
- "$TRAVIS_BUILD_DIR/build.sh"
- tar --create --verbose --file="$ARCHIVE_NAME" --directory "$TRAVIS_BUILD_DIR/dist"
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file: $ARCHIVE_NAME
  on:
    repo: heroku/heroku-nodejs-plugin
    tags: true
