language: node_js
sudo: false
node_js:
- '10'
- '12'
- '13'
- '14'
- '15'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
os:
- linux
after_success:
- ./deploy.sh
